name: docker-pipeline
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build CI image
      run: docker build -t django-ci-cd -f Dockerfile.ci .

    - name: Run tests
      run: docker run --rm django-ci-cd

